# Generated by Django 5.2.6 on 2025-09-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=8)),
                ("archi_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "quote_request",
            },
        ),
    ]
