# Generated by Django 5.2.6 on 2025-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_quote_request", "0003_alter_architect_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="username",
            field=models.CharField(default="username", max_length=100, unique=True),
        ),
    ]
