# Generated by Django 5.2.6 on 2025-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_quote_request", "0004_alter_architect_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="architect",
            name="role",
            field=models.CharField(
                choices=[("archi", "Archi"), ("secretaire", "Secrétaire")],
                default="secretaire",
                max_length=20,
            ),
        ),
    ]
