# Generated by Django 5.2.6 on 2025-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_quote_request", "0005_architect_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="role",
            field=models.CharField(choices=[("archi", "Archi")], max_length=20),
        ),
    ]
