# Generated by Django 5.2.6 on 2025-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_quote_request", "0006_alter_architect_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
