# Generated by Django 5.2.6 on 2025-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_quote_request", "0007_alter_architect_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architect",
            name="role",
            field=models.CharField(
                choices=[("archi", "Archi"), ("secretary", "Secretary")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="architect",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
